In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(4,7,3)

array([4. , 5.5, 7. ])

In [19]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [20]:
np.eye(20,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [21]:
np.random.rand(5,8)

array([[0.13562193, 0.03609605, 0.69087915, 0.44233257, 0.14625703,
        0.03025455, 0.93680082, 0.17009834],
       [0.45838454, 0.88692139, 0.16781189, 0.65433528, 0.50298166,
        0.36279536, 0.5475954 , 0.04966579],
       [0.05373323, 0.84913754, 0.13497028, 0.03443873, 0.3521575 ,
        0.7686791 , 0.93162957, 0.5495353 ],
       [0.47932042, 0.53259852, 0.83722487, 0.07239642, 0.2341425 ,
        0.54644908, 0.57448158, 0.79586526],
       [0.67193675, 0.57392163, 0.49064173, 0.29062647, 0.33624762,
        0.26803513, 0.11111815, 0.47238715]])

In [22]:
np.random.rand(5,8)

array([[0.0854265 , 0.35339853, 0.49724792, 0.47279462, 0.28954532,
        0.79538453, 0.62771081, 0.24416746],
       [0.95631746, 0.57639665, 0.83807315, 0.07244706, 0.63801189,
        0.76844321, 0.79583772, 0.34701407],
       [0.44061079, 0.07347035, 0.87148588, 0.64461676, 0.5309068 ,
        0.32911882, 0.74749715, 0.92169838],
       [0.56859788, 0.24018275, 0.38857823, 0.92450218, 0.37396181,
        0.57903809, 0.49603363, 0.31561488],
       [0.96933516, 0.86038359, 0.60408715, 0.07904982, 0.37798897,
        0.47596991, 0.33370208, 0.97552295]])

In [26]:
arr=np.random.rand(2,4)
arr

array([[0.23432439, 0.07219241, 0.42169734, 0.19065833],
       [0.56832206, 0.17371567, 0.11078377, 0.88414198]])

In [27]:
arr=np.random.rand(2,4)
arr

array([[0.81040813, 0.55750031, 0.90966102, 0.13759581],
       [0.71699885, 0.13596998, 0.98529524, 0.1462561 ]])

In [28]:
arr=np.random.rand(2,4)
arr

array([[0.87348864, 0.71314657, 0.98615478, 0.05716836],
       [0.84560702, 0.03259294, 0.45512356, 0.63298708]])

In [29]:
arr=np.random.rand(2,4)
arr

array([[0.89150222, 0.37943202, 0.97331849, 0.52949535],
       [0.3937318 , 0.11178277, 0.22623164, 0.76105   ]])

In [30]:
np.random.randint(2,100)

60

In [31]:
np.random.randint(20,56,100)

array([55, 44, 45, 27, 28, 40, 27, 42, 42, 55, 29, 40, 51, 54, 22, 30, 29,
       30, 34, 49, 29, 52, 49, 34, 52, 51, 20, 43, 39, 37, 50, 24, 28, 22,
       29, 30, 50, 47, 25, 28, 42, 48, 26, 36, 29, 34, 54, 44, 31, 53, 26,
       25, 24, 51, 55, 49, 35, 46, 22, 39, 29, 29, 37, 44, 21, 27, 32, 30,
       45, 28, 55, 48, 43, 27, 25, 41, 23, 26, 21, 43, 52, 42, 22, 39, 44,
       38, 39, 40, 53, 38, 29, 37, 24, 43, 37, 42, 43, 45, 51, 31])

In [33]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
rand_array=np.random.randint(0,10,50)
rand_array

array([8, 9, 9, 8, 0, 7, 0, 3, 5, 1, 1, 6, 6, 7, 0, 7, 9, 7, 6, 9, 5, 4,
       7, 3, 3, 1, 2, 4, 7, 1, 3, 2, 7, 8, 6, 4, 8, 8, 3, 2, 4, 1, 1, 9,
       1, 4, 0, 9, 1, 8])

In [36]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

ValueError: cannot reshape array of size 30 into shape (6,8)